### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by MingweiSamuel** [MingweiSamuel/TeemoJS#8]
Some improvements for version 2 of TeemoJS.

- [x] Multiple/separate LoL vs TFT (vs Tournament) api keys 9c715fb2781361e67c32d5f527949690122f179f
  - [x] With separate rate limiting
- [x] Region to platform translation, separate standard `eune->eun1`, TFT `eune->europe`, and tournament `*->americas` 5ccccfe2540ffda9f4149ba62e3c5e2855dbe869
- [x] Replace `request`. Quite an old, clunky library. Is in maintenance-only mode: https://github.com/request/request/issues/3142.
  - Use [node-fetch](https://www.npmjs.com/package/node-fetch) & `window.fetch`.
- [x] Properly handle all error cases. Currently error cases aren't handle consistently, i.e. 403 will return the parsed (error) body, while 400 will throw an exception (IIRC).
- [x] Use async/await for readability
- [x] Add support for non-GET requests/the tournament endpoints #7
- [x] Change rate limit config. Currently config is trapped in a lower layer, parameters are very unintuitive. The configuration used by [Riven](https://github.com/MingweiSamuel/Riven) is more intuitive and seems to be better at preventing 429s. Testing needed. 778ecc713626993a44953e6352488622ca72806c
- [x] Add a DDragon config #4.
- [x] Add a CDragon config.
- [x] Add https://github.com/meraki-analytics/kernel config, support in-browser. f64bae30e4a186eca26800ccd962d9bf331ecf25
- [x] Update tests to be key-agnostic, not use hardcoded encrypted ids. 93a6125b8e2fc7720fbb978aaedd0beacb423465

Bugs:
- [ ] RateLimit static method uses `this`, resulting in undefined `distFactor` https://github.com/MingweiSamuel/TeemoJS/blob/9614a453c66cda2603975d592b9460b0462937d7/src/index.js#L263
- [ ] unused second arg to new Region https://github.com/MingweiSamuel/TeemoJS/blob/9614a453c66cda2603975d592b9460b0462937d7/src/index.js#L138
- [ ] call to _getRegion missing key arg https://github.com/MingweiSamuel/TeemoJS/blob/9614a453c66cda2603975d592b9460b0462937d7/src/index.js#L125

**Comment by MingweiSamuel** [comment]
Version 2 is dead, on to version 3.
